services:
  - type: web
    name: brickify-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70

  - type: web
    name: brickify-ai
    env: docker
    dockerfilePath: Dockerfile
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
    envVars:
      - key: PORT
        value: 8001

databases:
  - name: brickify-db
    plan: free